services:
    app:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: toko-kue-app
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - toko-kue-net

    webserver:
        image: nginx:alpine
        container_name: toko-kue-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - toko-kue-net

    db:
        image: mysql:8.0
        container_name: toko-kue-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: toko_kue
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_USER: toko
            MYSQL_PASSWORD: tokopass
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - toko-kue-net
        
    redis:
        image: redis:alpine
        container_name: toko-kue-redis
        networks:
            - toko-kue-net

networks:
    toko-kue-net:
        driver: bridge

volumes:
    db-data: